Add Bundler 2.6 to docs site, and a release blog post
rubygems/bundler-site pull request #1416
Opened 2024-12-16 20:25 UTC by deivid-rodriguez

### What was the end-user problem that led to this PR?

The problem was that Bundler 2.6 is still not included in the documentation site, and that we should present the new stuff in Bundler 2.6.

### What is your fix for the problem, implemented in this PR?

My fix is to add the new version to documentation and write a blog post about it.

2024-12-16 20:39 UTC, simi approved these changes

2024-12-17 08:03 UTC, olleolleolle approved these changes
Thanks for blogging so well!

2024-12-17 08:03 UTC, olleolleolle commented on source/blog/2024-12-18-bundler-v2-6.html.markdown
> +recorded in the Gemfile.lock is stable, the most optimal platform specific
```suggestion
recorded in the Gemfile.lock is stable, the most optimal platform-specific
```

2024-12-17 08:03 UTC, olleolleolle commented on source/blog/2024-12-18-bundler-v2-6.html.markdown
> +able to keep a consistent lockfile with all platform specific variants, and use
```suggestion
able to keep a consistent lockfile with all platform-specific variants, and use
```

2024-12-17 08:03 UTC, olleolleolle commented on source/blog/2024-12-18-bundler-v2-6.html.markdown
> +the one that works best for each Ruby versiom.
```suggestion
the one that works best for each Ruby version.
```

2024-12-17 08:03 UTC, olleolleolle commented on source/blog/2024-12-18-bundler-v2-6.html.markdown
> +details.
```suggestion
And like always, many other bug fixes and improvements were implemented. Check
[the full Bundler 2.6 changelog](https://github.com/rubygems/rubygems/releases/tag/bundler-v2.6.0) for
details.
```

2024-12-17 14:01 UTC, tnir requested changes
@deivid-rodriguez Thanks for updating, but we need to update https://bundler.io/compatibility.html (source: https://github.com/rubygems/bundler-site/blob/master/source/compatibility.html.haml)

2024-12-17 15:07 UTC, deivid-rodriguez commented
> Thanks for blogging so well!

Haha, not so sure about that... 😅, but thank you!

> @deivid-rodriguez Thanks for updating, but we need to update https://bundler.io/compatibility.html (source: https://github.com/rubygems/bundler-site/blob/master/source/compatibility.html.haml)

Nice catch, let me update that now!

2024-12-18 20:14 UTC, deivid-rodriguez commented
I'll update blog post date and publish this tomorrow. If @tnir doesn't get to it, we can iterate after merge if everything else is needed.

2024-12-19 17:26 UTC, merged

2024-12-20 04:28 UTC, tnir commented
@deivid-rodriguez Thanks 🌮 and sorry for the delayed response! 🎉

2024-12-20 12:15 UTC, deivid-rodriguez commented
No problem, thanks for your review!